### ISSUE TITLE
get_abonents error (lastName)

### ISSUE THREAD

**Issue by it2shans** [bzdvdn/beeline_portal#3]
def from_beeline_struct(cls, beeline_struct: dict) -> 'Abonent':
        return cls(
            beeline_struct['userId'],
            beeline_struct.get('lastName'), # исправил метод на get, иначе будет ошибка KeyError: 'lastName'
            beeline_struct.get('firstName'),
            beeline_struct.get('phone'),
            beeline_struct.get('extension'),
            beeline_struct.get('email'),
            beeline_struct.get('department'),
        )

**Comment by bzdvdn** [comment]
fix in 0.0.5 version
